### ISSUE TITLE
`lch()` and `lab()` in `formatCss` has no `%`

### ISSUE THREAD

**Issue by ai** [Evercoder/culori#193]
In Culori 3.0.1 `formatCss(lch(color))` returns `lch(64.33 48.77 43.25)` without `%` for `L` component, which is invalid syntax (by Culori too).

Seems like it is 3.x regression.

**Comment by danburzo** [comment]
Hi @ai, this was a breaking change included in the 3.x release:

> `lab` and `lch` serialize the `L` component as `<number>`, not `<percentage>`

This was included to align with the [latest CSS Level 4 spec](https://drafts.csswg.org/css-color/#serializing-lab-lch).

Culori 3.x should be able to parse L as `<number>` in `lab()` and `lch()`. Can you share a snippet so I can get a better idea?

**Comment by ai** [comment]
Got it. I misread this part of migration guide.

**Comment by danburzo** [comment]
Ah, maybe I should have included a note about that in the migration guide as well (it's only in the release notes), but I was not sure what change to suggest. Browsers and Culori will accept either format for `lab()` / `lch()` and for `L` the result is identical whether specified as number or percentage, since its range is `[0, 100]`.
